# Generated by Django 5.2.6 on 2025-10-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurantinspection",
            name="BBL",
        ),
        migrations.RemoveField(
            model_name="restaurantinspection",
            name="BIN",
        ),
        migrations.RemoveField(
            model_name="restaurantinspection",
            name="Latitude",
        ),
        migrations.RemoveField(
            model_name="restaurantinspection",
            name="Location_Point1",
        ),
        migrations.RemoveField(
            model_name="restaurantinspection",
            name="Longitude",
        ),
        migrations.RemoveField(
            model_name="restaurantinspection",
            name="NTA",
        ),
        migrations.RemoveField(
            model_name="restaurantinspection",
            name="RECORD_DATE",
        ),
        migrations.AlterField(
            model_name="restaurantinspection",
            name="Census_Tract",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurantinspection",
            name="Community_Board",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurantinspection",
            name="Council_District",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurantinspection",
            name="SCORE",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurantinspection",
            name="ZIPCODE",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
