# Generated by Django 5.2.6 on 2025-10-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0002_remove_restaurantinspection_bbl_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camis", models.BigIntegerField()),
                ("restaurant_name", models.CharField(max_length=255)),
                ("reviewer_name", models.CharField(max_length=100)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("review_text", models.TextField()),
                ("review_date", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-review_date"],
            },
        ),
    ]
