# Generated by Django 5.2.6 on 2025-10-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0003_restaurantreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camis", models.BigIntegerField(unique=True)),
                ("restaurant_name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_formatted",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "monday_hours",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '9:00 AM - 10:00 PM' or 'Closed'",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tuesday_hours",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "wednesday_hours",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "thursday_hours",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "friday_hours",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "saturday_hours",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "sunday_hours",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "menu_highlights",
                    models.TextField(
                        blank=True, help_text="Popular dishes, specialties", null=True
                    ),
                ),
                (
                    "price_range",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '$', '$$', '$$$', '$$$$'",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("delivery_available", models.BooleanField(default=False)),
                ("takeout_available", models.BooleanField(default=True)),
                ("reservations_accepted", models.BooleanField(default=False)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Restaurant description/about", null=True
                    ),
                ),
                (
                    "special_features",
                    models.TextField(
                        blank=True,
                        help_text="Outdoor seating, live music, etc.",
                        null=True,
                    ),
                ),
                (
                    "parking_info",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
    ]
