# Generated by Django 5.2.6 on 2025-10-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0004_restaurantdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("camis", models.BigIntegerField()),
                ("restaurant_name", models.CharField(max_length=255)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_added"],
                "unique_together": {("session_key", "camis")},
            },
        ),
    ]
