# Generated by Django 5.2.6 on 2025-10-22 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0005_favoriterestaurant"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowedRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("camis", models.BigIntegerField()),
                ("restaurant_name", models.CharField(max_length=255)),
                ("date_followed", models.DateTimeField(auto_now_add=True)),
                ("notify_grade_changes", models.BooleanField(default=True)),
                ("notify_new_inspections", models.BooleanField(default=True)),
                ("notify_violations", models.BooleanField(default=True)),
                (
                    "last_known_grade",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("last_inspection_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date_followed"],
                "unique_together": {("session_key", "camis")},
            },
        ),
        migrations.CreateModel(
            name="RestaurantNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("grade_change", "Grade Change"),
                            ("new_inspection", "New Inspection"),
                            ("violation_added", "Violation Added"),
                            ("score_improvement", "Score Improvement"),
                            ("score_decline", "Score Decline"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "followed_restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inspections.followedrestaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
