# Generated by Django 5.2.6 on 2025-10-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0006_add_follow_notification_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("grade_change", "Grade Change"),
                    ("new_inspection", "New Inspection"),
                    ("violation_added", "Violation Added"),
                    ("score_improvement", "Score Improvement"),
                    ("score_decline", "Score Decline"),
                    ("health_outbreak", "Health Outbreak"),
                ],
                max_length=20,
            ),
        ),
    ]
