# Generated by Django 5.2.6 on 2025-11-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0007_alter_restaurantnotification_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantMonthlySales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camis", models.BigIntegerField()),
                ("month", models.DateField()),
                ("sales", models.FloatField()),
            ],
            options={
                "ordering": ["-month"],
                "unique_together": {("camis", "month")},
            },
        ),
    ]
